"""
src/api/email_alert.py
-------------------------
APEX Phase 3 — SMTP email alert for CRITICAL zone entry.

Reads credentials from environment variables (populated via .env loaded by
python-dotenv at startup). Falls back gracefully when not configured.
"""

from __future__ import annotations

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_critical_alert(
    machine_id: str,
    machine_name: str,
    machine_type: str,
    component: str,
    rul_mean: float,
    rul_std: float,
    fail_prob: float,
    recipient: str | None = None,
    recommendation: str = "",
) -> bool:
    """Send email alert when machine enters CRITICAL zone.

    Returns True if sent successfully, False otherwise (misconfigured / error).
    """
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASSWORD", "")
    recipient = recipient or os.getenv("ALERT_DEFAULT_RECIPIENT", "")

    if not smtp_user or not smtp_pass or not recipient:
        print(f"[EMAIL] Skipping alert — SMTP credentials not configured")
        return False

    subject = f"⚠ CRITICAL ALERT: {machine_name} requires immediate attention"

    default_rec = (
        f"Stop {machine_name} within the next shift and replace "
        f"{component.lower()} assembly. Estimated downtime if failure occurs "
        f"in-service: 14 hours vs 3 hours if replaced now."
    )

    html_body = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: #dc2626; color: white; padding: 16px 24px; border-radius: 8px 8px 0 0;">
            <h2 style="margin: 0;">CRITICAL MAINTENANCE ALERT</h2>
            <p style="margin: 4px 0 0; opacity: 0.9;">APEX Predictive Maintenance System</p>
        </div>
        <div style="border: 1px solid #e5e7eb; border-top: none; padding: 24px; border-radius: 0 0 8px 8px; background: #111827; color: #e5e7eb;">
            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px 0; color: #9ca3af;">Machine</td>
                    <td style="padding: 8px 0; font-weight: bold;">{machine_name}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; color: #9ca3af;">Type</td>
                    <td style="padding: 8px 0;">{machine_type}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; color: #9ca3af;">Failing component</td>
                    <td style="padding: 8px 0; font-weight: bold; color: #dc2626;">{component}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; color: #9ca3af;">Remaining useful life</td>
                    <td style="padding: 8px 0; font-weight: bold;">{rul_mean:.1f} ± {rul_std:.1f} cycles</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; color: #9ca3af;">Failure probability (30 cycles)</td>
                    <td style="padding: 8px 0; font-weight: bold; color: #dc2626;">{fail_prob * 100:.0f}%</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; color: #9ca3af;">Alert generated</td>
                    <td style="padding: 8px 0;">{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</td>
                </tr>
            </table>
            <div style="margin-top: 16px; padding: 12px; background: rgba(220,38,38,0.15); border-radius: 6px; border-left: 4px solid #dc2626;">
                <strong>Recommended action:</strong><br/>
                {recommendation or default_rec}
            </div>
            <p style="margin-top: 16px; font-size: 12px; color: #6b7280;">
                This alert was generated by APEX Predictive Maintenance Advisor.<br/>
                TENSOR '26 Hackathon · Team APEX · PS07
            </p>
        </div>
    </div>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = recipient
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, recipient, msg.as_string())
        print(f"[EMAIL] Alert sent to {recipient} for {machine_name}")
        return True
    except Exception as e:
        print(f"[EMAIL] Failed to send alert: {e}")
        return False
